### ISSUE TITLE
Php curl Exception during install 

### ISSUE THREAD

**Issue by Thiblef** [open-orchestra/open-orchestra-docs#111]
When running `./composer.phar create-project open-orchestra/open-orchestra ./open-orchestra -s dev --ignore-platform-reqs` get the error:

`[Guzzle\Common\Exception\RuntimeException]               
  The PHP cURL extension must be installed to use Guzzle.`

Due to the execution of the script:
`Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache`

**Comment by alavieille** [comment]
fix in this PR https://github.com/open-orchestra/open-orchestra-docs/pull/116/files
