### ISSUE TITLE
Add git install in Hosting_guide/requirements

### ISSUE THREAD

**Issue by mraiffe** [open-orchestra/open-orchestra-docs#144]
To deploy with capistrano (or other method) git must be installed on the integration server.

**Comment by nicolasThal** [comment]
This requirement should be added to this doc : https://github.com/open-orchestra/open-orchestra-docs/blob/master/en/hosting_guide/deploy.rst

**Comment by mraiffe** [comment]
Composer must be installed and ACL parameted

**Comment by mraiffe** [comment]
:+1:
