### ISSUE TITLE
Dev left panel - how to link different kind of pages

### ISSUE THREAD

**Issue by juchi** [open-orchestra/open-orchestra-docs#45]
The dev doc about the left panel misses information about the importance of the "href" value and how it should be used depending on the kind of page that will be displayed.

The method addRoutePattern may also be explained in order to extend the native behavior.

**Comment by nicolasThal** [comment]
Does this documentation fullfill your questions ?

https://github.com/open-orchestra/open-orchestra-docs/blob/master/en/developer_guide/navigation_panel.rst

**Comment by juchi** [comment]
The method addRoutePattern is not explained, I still think it would be nice.
Line 33, I guess "should" is not appropriate, maybe use "must" ?

**Comment by nicolasThal** [comment]
Complete the doc with some code :
- attribute to put
- javascript to modify
- possibilities

**Comment by ghost** [comment]
Completed in https://github.com/open-orchestra/open-orchestra-docs/pull/125
