### ISSUE TITLE
Add developpers guide for Media and media references

### ISSUE THREAD

**Issue by clement-michelet** [open-orchestra/open-orchestra-docs#61]
No documentation is available for media integration with document.

We should have an explanation on :
- how to have direct usage of Media or a reference (DAM) to a Media
- the workflow of updating / deleting references

**Comment by nicolasThal** [comment]
In the roadmap

**Comment by raphaelcarles** [comment]
https://trello.com/c/z10qZHpB/1396-3-doc-on-media
